export const SERVICE_LIST = [
  { id: "s1", label: "Home Cleaning" },
  { id: "s2", label: "Deep Cleaning" },
  { id: "s3", label: "Office Cleaning" },
  { id: "s4", label: "Sweeping" },
  { id: "s5", label: "Mopping" },
  { id: "s6", label: "Dusting" },
  { id: "s7", label: "Bathroom Cleaning" },
  { id: "s8", label: "Kitchen Cleaning" },
  { id: "s9", label: "Window Cleaning" },
  { id: "s10", label: "Laundry / Clothes Washing" },
  { id: "s11", label: "Ironing Clothes" },
  { id: "s12", label: "Dish Washing" },
  { id: "s13", label: "Cooking" },
  { id: "s14", label: "Meal Preparation" },
  { id: "s15", label: "Bedroom Cleaning" },
  { id: "s16", label: "Living Room Cleaning" },
  { id: "s17", label: "Floor Cleaning" },
  { id: "s18", label: "Carpet Cleaning" },
  { id: "s19", label: "Sofa Cleaning" },
  { id: "s20", label: "Organizing / General Household Help" },
];